### ISSUE TITLE
Failed on release build

### ISSUE THREAD

**Issue by ahmedmirza994** [ajaynonstopio/connectivity_wrapper#9]
On release build, it always shows there is no internet connection but on debug build it works fine.

**Comment by BilalKashif** [comment]
same Issue.

**Comment by BilalKashif** [comment]
> 
> 
> On release build, it always shows there is no internet connection but on debug build it works fine.

Hello Brother, 
I've found the solution to this issue.
This is hapening because you did't give permission to internet in your AndroidManifest.xml file of your app.
just add
 `<manifest xmlns:android="...">`
  `<uses-permission android:name="android.permission.INTERNET"/> <!-- Add this -->`
 `</manifast>`

permission like this and done.
